#%RAML 1.0
version: v1
baseUri: http://myapi.mysite.com/api/{version}
title: muletestdpj

/hello:
  get:
    responses:
      200:
        body:
          application/json:
            example: {'reply':'hello'}